spring:
  application:
    name: SpringJWT

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          #        show_sql: true
          format_sql: true

  datasource:

    #    kdy
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: ehd5765613
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: 795a494eb4ca40d62227cc695a41e69d1e13fa5da2263727c28ba073fdbdd2f2